import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from 'react';
import { loadAdapters } from '../../adapters';
export default function MembersPage() {
    const [rows, setRows] = useState([]);
    const [repos, setRepos] = useState(null);
    const [edit, setEdit] = useState(null);
    const load = async () => { if (!repos)
        return; setRows(await repos.memberRepo.list()); };
    useEffect(() => { (async () => { const a = await loadAdapters(); setRepos(a); })(); }, []);
    useEffect(() => { if (repos)
        load(); }, [repos]);
    return (_jsxs("div", { className: "space-y-3", children: [_jsx("div", { className: "text-lg font-semibold", children: "\u6703\u54E1\u7BA1\u7406" }), _jsxs("div", { className: "rounded-2xl bg-white p-2 shadow-card", children: [rows.map(m => (_jsxs("div", { className: "flex items-center justify-between border-b p-3 text-sm", children: [_jsxs("div", { children: [_jsxs("div", { className: "font-semibold", children: [m.name, " ", _jsx("span", { className: "text-xs text-gray-500", children: m.code })] }), _jsxs("div", { className: "text-xs text-gray-500", children: [m.email || '-', "\uFF5C", m.phone || '-', "\uFF5C\u7A4D\u5206 ", m.points || 0] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("button", { onClick: () => navigator.clipboard.writeText(m.code), className: "rounded bg-gray-100 px-3 py-1", children: "\u8907\u88FD\u7DE8\u865F" }), _jsx("button", { onClick: () => setEdit(m), className: "rounded bg-gray-900 px-3 py-1 text-white", children: "\u7DE8\u8F2F" })] })] }, m.id))), rows.length === 0 && _jsx("div", { className: "p-4 text-center text-gray-500", children: "\u5C1A\u7121\u6703\u54E1" })] }), edit && (_jsx("div", { className: "fixed inset-0 z-50 grid place-items-center bg-black/30 p-4", children: _jsxs("div", { className: "w-full max-w-md rounded-2xl bg-white p-4 shadow-card", children: [_jsx("div", { className: "mb-2 text-lg font-semibold", children: "\u7DE8\u8F2F\u6703\u54E1" }), _jsxs("div", { className: "space-y-2 text-sm", children: [_jsx("input", { className: "w-full rounded border px-2 py-1", placeholder: "\u59D3\u540D", value: edit.name, onChange: e => setEdit({ ...edit, name: e.target.value }) }), _jsx("input", { className: "w-full rounded border px-2 py-1", placeholder: "Email", value: edit.email || '', onChange: e => setEdit({ ...edit, email: e.target.value }) }), _jsx("input", { className: "w-full rounded border px-2 py-1", placeholder: "\u624B\u6A5F", value: edit.phone || '', onChange: e => setEdit({ ...edit, phone: e.target.value }) })] }), _jsxs("div", { className: "mt-3 flex justify-end gap-2", children: [_jsx("button", { onClick: () => setEdit(null), className: "rounded bg-gray-100 px-3 py-1", children: "\u53D6\u6D88" }), _jsx("button", { onClick: async () => { if (!repos)
                                        return; await repos.memberRepo.upsert(edit); setEdit(null); load(); }, className: "rounded bg-brand-500 px-3 py-1 text-white", children: "\u5132\u5B58" })] })] }) }))] }));
}
