import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { SectionTitle } from '../kit';
import { authRepo } from '../../adapters/local/auth';
import { useNavigate } from 'react-router-dom';
export default function PageProfile() {
    const u = authRepo.getCurrentUser();
    const nav = useNavigate();
    const roleZh = u?.role === 'admin' ? '管理員' : u?.role === 'support' ? '客服' : u?.role === 'sales' ? '業務' : u?.role === 'technician' ? '外勤人員' : '會員';
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: "h-20 w-20 rounded-full bg-gray-200" }), _jsxs("div", { children: [_jsx("div", { className: "text-lg font-semibold", children: roleZh }), _jsxs("div", { className: "text-sm text-gray-500", children: [u?.name || '-', "\uFF5C", u?.email || '-', "\uFF5C\u65E5\u5F0F\u6D17\u6FEF\u6709\u9650\u516C\u53F8"] })] })] }), _jsxs("div", { className: "rounded-2xl bg-white p-4 shadow-card", children: [_jsx(SectionTitle, { children: "\u5E33\u865F\u8CC7\u8A0A" }), _jsxs("div", { className: "mt-3 space-y-3 text-sm", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-gray-500", children: "\u59D3\u540D" }), _jsx("span", { children: u?.name || '-' })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-gray-500", children: "\u5E33\u865F" }), _jsx("span", { children: u?.email || '-' })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-gray-500", children: "\u5EE0\u5546" }), _jsx("span", { children: "\u65E5\u5F0F\u6D17\u6FEF\u6709\u9650\u516C\u53F8" })] })] })] }), _jsxs("div", { className: "rounded-2xl bg-white p-4 shadow-card", children: [_jsx(SectionTitle, { children: "\u5B89\u5168\u6027" }), _jsx("div", { className: "mt-3 space-y-3 text-sm", children: _jsx("button", { onClick: () => nav('/reset-password'), className: "w-full rounded-xl bg-gray-900 py-3 text-white", children: "\u8B8A\u66F4\u5BC6\u78BC" }) })] })] }));
}
