import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from 'react';
import { staffRepo } from '../../adapters/local/staff';
import { authRepo } from '../../adapters/local/auth';
import { Navigate } from 'react-router-dom';
import { getPermissionOverride, setPermissionOverride } from '../../utils/permissions';
export default function StaffManagementPage() {
    const u = authRepo.getCurrentUser();
    if (u && u.role !== 'admin')
        return _jsx(Navigate, { to: "/dispatch", replace: true });
    const [rows, setRows] = useState([]);
    const [edit, setEdit] = useState(null);
    const load = async () => setRows(await staffRepo.list());
    useEffect(() => { load(); }, []);
    return (_jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("div", { className: "text-lg font-semibold", children: "\u54E1\u5DE5\u7BA1\u7406" }), _jsx("button", { onClick: () => setEdit({ name: '', email: '', role: 'support', status: 'active' }), className: "rounded-lg bg-brand-500 px-3 py-1 text-white", children: "\u65B0\u589E" })] }), rows.map(s => (_jsxs("div", { className: "rounded-xl border p-4 shadow-card", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsxs("div", { className: "font-semibold", children: [s.name, " ", _jsx("span", { className: "text-xs text-gray-500", children: s.refCode || '' })] }), _jsxs("div", { className: "text-xs text-gray-500", children: [s.email, "\uFF5C", s.role, "\uFF5C", s.status, "\uFF5C\u7A4D\u5206 ", s.points || 0] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [s.refCode && _jsx("button", { onClick: () => navigator.clipboard.writeText(s.refCode), className: "rounded-lg bg-gray-100 px-3 py-1 text-sm", children: "\u8907\u88FD\u7DE8\u865F" }), _jsx("button", { onClick: () => setEdit(s), className: "rounded-lg bg-gray-900 px-3 py-1 text-white", children: "\u7DE8\u8F2F" }), _jsx("button", { onClick: async () => { const { confirmTwice } = await import('../kit'); if (await confirmTwice('確認刪除該員工？', '刪除後無法復原，仍要刪除？')) {
                                            await staffRepo.remove(s.id);
                                            load();
                                        } }, className: "rounded-lg bg-rose-500 px-3 py-1 text-white", children: "\u522A\u9664" }), _jsx("button", { onClick: async () => { await staffRepo.resetPassword(s.id); alert('已觸發重設密碼（示意）'); }, className: "rounded-lg bg-gray-100 px-3 py-1 text-sm", children: "\u91CD\u8A2D\u5BC6\u78BC" })] })] }), _jsx(PermissionOverrideEditor, { email: s.email })] }, s.id))), rows.length === 0 && _jsx("div", { className: "text-gray-500", children: "\u5C1A\u7121\u54E1\u5DE5" }), edit && (_jsx("div", { className: "fixed inset-0 z-50 grid place-items-center bg-black/30 p-4", children: _jsxs("div", { className: "w-full max-w-md rounded-2xl bg-white p-4 shadow-card", children: [_jsxs("div", { className: "mb-2 text-lg font-semibold", children: [edit.id ? '編輯' : '新增', "\u54E1\u5DE5"] }), _jsxs("div", { className: "space-y-2 text-sm", children: [_jsxs("div", { children: ["\u59D3\u540D\uFF1A", _jsx("input", { className: "w-full rounded border px-2 py-1", value: edit.name, onChange: e => setEdit({ ...edit, name: e.target.value }) })] }), _jsxs("div", { children: ["Email\uFF1A", _jsx("input", { className: "w-full rounded border px-2 py-1", value: edit.email, onChange: e => setEdit({ ...edit, email: e.target.value }) })] }), _jsxs("div", { children: ["\u89D2\u8272\uFF1A", _jsxs("select", { className: "w-full rounded border px-2 py-1", value: edit.role, onChange: e => setEdit({ ...edit, role: e.target.value }), children: [_jsx("option", { value: "support", children: "support" }), _jsx("option", { value: "sales", children: "sales" })] })] }), _jsxs("div", { children: ["\u72C0\u614B\uFF1A", _jsxs("select", { className: "w-full rounded border px-2 py-1", value: edit.status, onChange: e => setEdit({ ...edit, status: e.target.value }), children: [_jsx("option", { value: "active", children: "active" }), _jsx("option", { value: "suspended", children: "suspended" })] })] })] }), _jsxs("div", { className: "mt-3 flex justify-end gap-2", children: [_jsx("button", { onClick: () => setEdit(null), className: "rounded-lg bg-gray-100 px-3 py-1", children: "\u53D6\u6D88" }), _jsx("button", { onClick: async () => { await staffRepo.upsert(edit); setEdit(null); load(); }, className: "rounded-lg bg-brand-500 px-3 py-1 text-white", children: "\u5132\u5B58" })] })] }) }))] }));
}
function PermissionOverrideEditor({ email }) {
    const [open, setOpen] = useState(false);
    const [allow, setAllow] = useState([]);
    const [deny, setDeny] = useState([]);
    useEffect(() => {
        const ov = getPermissionOverride(email || '');
        setAllow(ov?.allow || []);
        setDeny(ov?.deny || []);
    }, [email]);
    const toggle = (list, val) => list.includes(val) ? list.filter(v => v !== val) : [...list, val];
    const ALL = ['orders.list', 'orders.create', 'orders.update', 'orders.delete', 'orders.cancel', 'reservations.manage', 'customers.manage', 'technicians.manage', 'technicians.schedule.view', 'technicians.schedule.edit', 'support.schedule.view', 'support.schedule.edit', 'staff.manage', 'products.manage', 'inventory.manage', 'promotions.manage', 'documents.manage', 'models.manage', 'notifications.send', 'approvals.manage', 'payroll.view', 'payroll.edit', 'reports.view', 'reports.manage'];
    return (_jsxs("div", { className: "mt-2", children: [_jsx("button", { onClick: () => setOpen(o => !o), className: "rounded bg-gray-100 px-2 py-1 text-xs", children: open ? '收起權限覆蓋' : '編輯權限覆蓋' }), open && (_jsxs("div", { className: "mt-2 rounded border p-2", children: [_jsx("div", { className: "text-xs text-gray-600", children: "\u5141\u8A31\uFF08Allow\uFF09" }), _jsx("div", { className: "mt-1 grid grid-cols-2 gap-1", children: ALL.map(p => (_jsxs("label", { className: "flex items-center gap-1 text-xs", children: [_jsx("input", { type: "checkbox", checked: allow.includes(p), onChange: e => setAllow(toggle(allow, p)) }), p] }, `a-${p}`))) }), _jsx("div", { className: "mt-2 text-xs text-gray-600", children: "\u62D2\u7D55\uFF08Deny\uFF09" }), _jsx("div", { className: "mt-1 grid grid-cols-2 gap-1", children: ALL.map(p => (_jsxs("label", { className: "flex items-center gap-1 text-xs", children: [_jsx("input", { type: "checkbox", checked: deny.includes(p), onChange: e => setDeny(toggle(deny, p)) }), p] }, `d-${p}`))) }), _jsx("div", { className: "mt-2 text-right", children: _jsx("button", { onClick: () => { setPermissionOverride(email, { allow: allow, deny: deny }); alert('已儲存覆蓋'); }, className: "rounded bg-brand-500 px-3 py-1 text-xs text-white", children: "\u5132\u5B58\u8986\u84CB" }) })] }))] }));
}
